"""
Shared runtime configuration and trajectory helpers for training and inference.

This module centralizes:
- config loading
- seeding
- mapping knowledge templates to token-space subgraphs for Hard Import
- sampling full patient trajectories for RL rollouts

Entry points:
- warmup.py : Stage 1 encoder warm-up
- rl_train.py: Stage 2 REINFORCE policy learning + encoder refinement
"""

from __future__ import annotations

import json
import hashlib
import math
import os
import random
from dataclasses import dataclass, field
from typing import Any, Callable, Dict, List, Mapping, Optional, Sequence, Set

import numpy as np
import torch

try:
    import yaml
except Exception:
    yaml = None


if yaml is not None:
    class _UniqueKeySafeLoader(yaml.SafeLoader):
        """Safe YAML loader that rejects duplicate keys at every depth."""

        def construct_mapping(self, node, deep=False):
            self.flatten_mapping(node)
            mapping = {}
            for key_node, value_node in node.value:
                key = self.construct_object(key_node, deep=deep)
                if key in mapping:
                    raise ValueError(f"duplicate YAML mapping key {key!r} is not allowed")
                mapping[key] = self.construct_object(value_node, deep=deep)
            return mapping
else:
    _UniqueKeySafeLoader = None

from .model import TemplateSubgraph


CHECKPOINT_FORMAT_VERSION = 2
RETRIEVAL_SPACE = "learnable_code_embedding_gru_state_v1"


@dataclass
class DataConfig:
    processed_path: str = "data/processed/processed.pt"
    batch_size: int = 32
    split_json: Optional[str] = None
    train_split: str = "train"


@dataclass
class KnowledgeConfig:
    templates_jsonl: str = "data/knowledge/templates.jsonl"
    retrieval_K: int = 20
    retrieval_alpha: float = 0.3
    # Generated by `reta build-entity-map`; ICD:/CCS: ids come from processed.pt.
    entity_to_token_json: Optional[str] = "data/resources/entity_to_token.json"


@dataclass
class ModelConfig:
    dim: int = 256
    gnn_layers: int = 2
    attn_heads: int = 4
    dropout: float = 0.3


@dataclass
class OutputConfig:
    checkpoints_dir: str = "checkpoints"
    logs_dir: str = "logs"


@dataclass
class TrainConfig:
    seed: int = 42
    device: str = "auto"
    lr: float = 1e-4
    weight_decay: float = 1e-5
    grad_clip: float = 0.5

    # warmup
    warmup_epochs: int = 30
    exposure_prob: float = 0.3
    soft_xi: float = 0.5

    # RL
    rl_iters: int = 50
    rollout_patients: int = 64
    max_visits_per_patient: int = 50
    encoder_updates_per_iter: int = 1
    policy_lr: float = 1e-5
    gamma: float = 0.95
    baseline_decay: float = 0.99
    policy_entropy_coef: float = 0.0
    reward_lambda1: float = 1.0
    reward_lambda2: float = 0.1
    utility_decay: float = 0.95


@dataclass
class Config:
    data: DataConfig = field(default_factory=DataConfig)
    knowledge: KnowledgeConfig = field(default_factory=KnowledgeConfig)
    model: ModelConfig = field(default_factory=ModelConfig)
    outputs: OutputConfig = field(default_factory=OutputConfig)
    train: TrainConfig = field(default_factory=TrainConfig)


def load_config(path: Optional[str] = None) -> Config:
    cfg = Config()
    if path is None:
        validate_config(cfg)
        return cfg
    if yaml is None:
        raise ImportError("pyyaml is required to load config files.")
    with open(path, "r", encoding="utf-8") as f:
        d = yaml.load(f, Loader=_UniqueKeySafeLoader) or {}
    if not isinstance(d, dict):
        raise ValueError("config root must be a mapping")

    def update(dc, sub, section):
        if sub is None:
            return
        if not isinstance(sub, dict):
            raise ValueError(f"config section {section!r} must be a mapping")
        unknown = sorted(set(sub) - set(dc.__dataclass_fields__))
        if unknown:
            names = ", ".join(unknown)
            raise ValueError(f"unknown key(s) in config section {section!r}: {names}")
        for k, v in sub.items():
            setattr(dc, k, v)

    known_sections = {"data", "knowledge", "model", "outputs", "train"}
    unknown_sections = sorted(set(d) - known_sections)
    if unknown_sections:
        names = ", ".join(unknown_sections)
        raise ValueError(f"unknown config section(s): {names}")

    update(cfg.data, d.get("data"), "data")
    update(cfg.knowledge, d.get("knowledge"), "knowledge")
    update(cfg.model, d.get("model"), "model")
    update(cfg.outputs, d.get("outputs"), "outputs")
    update(cfg.train, d.get("train"), "train")
    validate_config(cfg)
    return cfg


def validate_config(cfg: Config) -> None:
    """Fail fast on invalid hyperparameters and runtime paths."""

    def require_path(name: str, value: Any, optional: bool = False) -> None:
        if optional and value is None:
            return
        if not isinstance(value, str) or not value.strip():
            raise ValueError(f"{name} must be a non-empty path string.")

    def require_int(name: str, value: Any, minimum: int = 1) -> None:
        if isinstance(value, bool) or not isinstance(value, int) or value < minimum:
            raise ValueError(f"{name} must be an integer >= {minimum}.")

    def require_number(name: str, value: Any, minimum: float = 0.0) -> float:
        if isinstance(value, bool) or not isinstance(value, (int, float)):
            raise ValueError(f"{name} must be numeric.")
        numeric = float(value)
        if not np.isfinite(numeric) or numeric < minimum:
            raise ValueError(f"{name} must be finite and >= {minimum}.")
        return numeric

    def require_probability(name: str, value: Any, upper_inclusive: bool = True) -> None:
        numeric = require_number(name, value)
        valid = numeric <= 1.0 if upper_inclusive else numeric < 1.0
        if not valid:
            bound = "[0, 1]" if upper_inclusive else "[0, 1)"
            raise ValueError(f"{name} must be in {bound}.")

    require_path("data.processed_path", cfg.data.processed_path)
    require_int("data.batch_size", cfg.data.batch_size)
    require_path("data.split_json", cfg.data.split_json, optional=True)
    if cfg.data.train_split not in {"train", "val", "test", "all"}:
        raise ValueError("data.train_split must be train, val, test, or all.")

    require_path("knowledge.templates_jsonl", cfg.knowledge.templates_jsonl)
    require_int("knowledge.retrieval_K", cfg.knowledge.retrieval_K)
    require_probability("knowledge.retrieval_alpha", cfg.knowledge.retrieval_alpha)
    require_path(
        "knowledge.entity_to_token_json",
        cfg.knowledge.entity_to_token_json,
        optional=True,
    )

    require_int("model.dim", cfg.model.dim)
    require_int("model.gnn_layers", cfg.model.gnn_layers)
    require_int("model.attn_heads", cfg.model.attn_heads)
    if cfg.model.dim % cfg.model.attn_heads != 0:
        raise ValueError("model.dim must be divisible by model.attn_heads.")
    require_probability("model.dropout", cfg.model.dropout, upper_inclusive=False)

    require_path("outputs.checkpoints_dir", cfg.outputs.checkpoints_dir)
    require_path("outputs.logs_dir", cfg.outputs.logs_dir)

    if not isinstance(cfg.train.seed, int) or isinstance(cfg.train.seed, bool):
        raise ValueError("train.seed must be an integer.")
    if not isinstance(cfg.train.device, str) or not cfg.train.device.strip():
        raise ValueError("train.device must be a non-empty device string.")
    require_number("train.lr", cfg.train.lr, minimum=1e-300)
    require_number("train.weight_decay", cfg.train.weight_decay)
    require_number("train.grad_clip", cfg.train.grad_clip, minimum=1e-300)
    require_int("train.warmup_epochs", cfg.train.warmup_epochs)
    require_probability("train.exposure_prob", cfg.train.exposure_prob)
    require_number("train.soft_xi", cfg.train.soft_xi)
    require_int("train.rl_iters", cfg.train.rl_iters)
    require_int("train.rollout_patients", cfg.train.rollout_patients)
    require_int("train.max_visits_per_patient", cfg.train.max_visits_per_patient, minimum=2)
    require_int("train.encoder_updates_per_iter", cfg.train.encoder_updates_per_iter)
    require_number("train.policy_lr", cfg.train.policy_lr, minimum=1e-300)
    require_probability("train.gamma", cfg.train.gamma)
    require_probability("train.baseline_decay", cfg.train.baseline_decay, upper_inclusive=False)
    require_number("train.policy_entropy_coef", cfg.train.policy_entropy_coef)
    require_number("train.reward_lambda1", cfg.train.reward_lambda1)
    require_number("train.reward_lambda2", cfg.train.reward_lambda2)
    require_probability("train.utility_decay", cfg.train.utility_decay, upper_inclusive=False)


def _integer_mapping(value: Optional[Mapping[str, Any]], label: str) -> Dict[str, int]:
    if value is None:
        return {}
    if not isinstance(value, Mapping):
        raise ValueError(f"{label} must map entity names to integer token IDs.")

    normalized: Dict[str, int] = {}
    for raw_name, raw_token in value.items():
        name = str(raw_name)
        if not name:
            raise ValueError(f"{label} contains an empty entity name.")
        if isinstance(raw_token, bool) or not isinstance(raw_token, int):
            raise ValueError(f"{label}[{name!r}] must be an integer token ID.")
        token = int(raw_token)
        if token < 0:
            raise ValueError(f"{label}[{name!r}] must be non-negative.")
        normalized[name] = token
    return normalized


def load_json_object_strict(path: str, label: str) -> Dict[str, Any]:
    """Load an object while rejecting duplicate keys and non-finite numbers."""

    def object_pairs(pairs):
        result = {}
        for key, value in pairs:
            if key in result:
                raise ValueError(f"{label} contains duplicate key {key!r}.")
            result[key] = value
        return result

    def reject_constant(value: str):
        raise ValueError(f"{label} contains non-finite value {value}.")

    def parse_float(value: str) -> float:
        parsed = float(value)
        if not math.isfinite(parsed):
            reject_constant(value)
        return parsed

    with open(path, "r", encoding="utf-8") as handle:
        value = json.load(
            handle,
            object_pairs_hook=object_pairs,
            parse_constant=reject_constant,
            parse_float=parse_float,
        )
    if not isinstance(value, dict):
        raise ValueError(f"{label} must contain a JSON object.")
    return value


def mapping_fingerprint(mapping: Mapping[str, Any]) -> str:
    normalized = _integer_mapping(mapping, "token mapping")
    payload = json.dumps(
        sorted(normalized.items()),
        ensure_ascii=False,
        separators=(",", ":"),
    ).encode("utf-8")
    return hashlib.sha256(payload).hexdigest()


def file_fingerprint(path: str) -> str:
    digest = hashlib.sha256()
    with open(path, "rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def load_checkpoint(path: str) -> Dict[str, Any]:
    """Load a tensor/basic-type checkpoint without allowing arbitrary pickle code."""

    value = torch.load(path, map_location="cpu", weights_only=True)
    if not isinstance(value, dict):
        raise ValueError("checkpoint root must be a dictionary.")
    return value


def load_processed_data(path: str) -> Dict[str, Any]:
    """Load a trusted, locally generated ``processed.pt`` dataset.

    Processed datasets contain NumPy objects and therefore cannot use Torch's
    restricted weights-only loader. Never open an untrusted processed file.
    """

    value = torch.load(path, map_location="cpu", weights_only=False)
    if not isinstance(value, dict):
        raise ValueError("processed dataset root must be a dictionary.")
    for key in ("trajectories", "meta", "vocab"):
        if not isinstance(value.get(key), dict):
            raise ValueError(f"processed dataset is missing mapping {key!r}.")
    return value


def build_checkpoint_contract(
    *,
    mapper: "EntityTokenMapper",
    processed_path: str,
    templates_path: str,
    split_json: Optional[str],
    training_split: str,
    icd_vocab_size: int,
    ccs_vocab_size: int,
    ccs_label_vocab_size: int,
    model_dim: int,
    gnn_layers: int,
    attn_heads: int,
    dropout: float,
    pool_dim: int,
    retrieval_K: int,
    retrieval_alpha: float,
    soft_xi: float,
) -> Dict[str, Any]:
    """Build the immutable data/model identity stored in every checkpoint."""

    icd_vocab_size = int(icd_vocab_size)
    ccs_vocab_size = int(ccs_vocab_size)
    ccs_label_vocab_size = int(ccs_label_vocab_size)
    if not 0 < ccs_label_vocab_size <= ccs_vocab_size:
        raise ValueError("ccs_label_vocab_size must be in [1, ccs_vocab_size].")
    if int(model_dim) <= 0 or int(pool_dim) <= 0:
        raise ValueError("model_dim and pool_dim must be positive.")
    if int(model_dim) != int(pool_dim):
        raise ValueError(
            f"knowledge pool dimension {pool_dim} must equal model dimension {model_dim}."
        )
    if int(gnn_layers) <= 0 or int(attn_heads) <= 0:
        raise ValueError("gnn_layers and attn_heads must be positive.")
    if int(model_dim) % int(attn_heads) != 0:
        raise ValueError("model_dim must be divisible by attn_heads.")
    if not 0.0 <= float(dropout) < 1.0:
        raise ValueError("dropout must be in [0, 1).")
    if int(retrieval_K) <= 0:
        raise ValueError("retrieval_K must be positive.")
    if not 0.0 <= float(retrieval_alpha) <= 1.0:
        raise ValueError("retrieval_alpha must be in [0, 1].")
    if not np.isfinite(float(soft_xi)) or float(soft_xi) < 0.0:
        raise ValueError("soft_xi must be non-negative.")
    if split_json is None and training_split != "all":
        raise ValueError("training_split must be 'all' when no split manifest is used.")
    if split_json is not None and training_split not in {"train", "val", "test"}:
        raise ValueError("training_split must be train, val, or test.")

    split_manifest_sha256 = file_fingerprint(split_json) if split_json else None
    split_identity = f"{split_manifest_sha256 or 'none'}:{training_split}"

    return {
        "format_version": CHECKPOINT_FORMAT_VERSION,
        "retrieval_space": RETRIEVAL_SPACE,
        "icd_vocab_size": icd_vocab_size,
        "ccs_vocab_size": ccs_vocab_size,
        "ccs_label_vocab_size": ccs_label_vocab_size,
        "base_vocab_size": icd_vocab_size + ccs_vocab_size,
        "vocab_size": mapper.vocab_size,
        "model_dim": int(model_dim),
        "gnn_layers": int(gnn_layers),
        "attn_heads": int(attn_heads),
        "dropout": float(dropout),
        "pool_dim": int(pool_dim),
        "retrieval_K": int(retrieval_K),
        "retrieval_alpha": float(retrieval_alpha),
        "soft_xi": float(soft_xi),
        "base_mapping_sha256": mapping_fingerprint(mapper.base_mapping),
        "external_mapping_sha256": mapping_fingerprint(mapper.external_mapping),
        "processed_sha256": file_fingerprint(processed_path),
        "templates_sha256": file_fingerprint(templates_path),
        "split_manifest_sha256": split_manifest_sha256,
        "training_split": training_split,
        "training_split_sha256": hashlib.sha256(
            split_identity.encode("utf-8")
        ).hexdigest(),
    }


def require_checkpoint_contract(
    checkpoint: Mapping[str, Any],
    current_contract: Mapping[str, Any],
) -> None:
    """Reject legacy, incomplete, or data-incompatible checkpoints."""

    stored = checkpoint.get("contract")
    if not isinstance(stored, Mapping):
        raise ValueError(
            "checkpoint has no ReTA format-v2 contract; retrain it with the current release."
        )
    missing = sorted(set(current_contract) - set(stored))
    if missing:
        raise ValueError("checkpoint contract is missing: " + ", ".join(missing))
    unexpected = sorted(set(stored) - set(current_contract))
    if unexpected:
        raise ValueError("checkpoint contract has unknown fields: " + ", ".join(unexpected))
    mismatches = [
        f"{key}: checkpoint={stored[key]!r}, current={current_contract[key]!r}"
        for key in current_contract
        if stored[key] != current_contract[key]
    ]
    if mismatches:
        raise ValueError("checkpoint contract mismatch: " + "; ".join(mismatches))


def load_state_dict_strict(module, state_dict: Mapping[str, Any], component: str) -> None:
    """Load a complete state dictionary with a component-specific error."""

    try:
        module.load_state_dict(state_dict, strict=True)
    except Exception as exc:
        raise ValueError(f"incompatible {component} state in checkpoint: {exc}") from exc


def load_split_manifest(path: str) -> Dict[str, Set[str]]:
    """Load patient splits and reject duplicates or cross-split leakage."""

    value = load_json_object_strict(path, "patient split file")

    result: Dict[str, Set[str]] = {}
    owner: Dict[str, str] = {}
    for raw_name, raw_ids in value.items():
        name = str(raw_name)
        if name not in {"train", "val", "test"}:
            raise ValueError(
                f"patient split name {name!r} must be train, val, or test."
            )
        if not isinstance(raw_ids, list):
            raise ValueError(f"patient split {name!r} must be a JSON list.")
        ids = []
        for patient_id in raw_ids:
            if isinstance(patient_id, bool) or not isinstance(patient_id, (str, int)):
                raise ValueError(
                    f"patient split {name!r} contains a non-string/non-integer ID."
                )
            ids.append(str(patient_id))
        if len(ids) != len(set(ids)):
            raise ValueError(f"patient split {name!r} contains duplicate IDs.")
        for patient_id in ids:
            previous = owner.get(patient_id)
            if previous is not None:
                raise ValueError(
                    f"a patient occurs in both {previous!r} and {name!r}."
                )
            owner[patient_id] = name
        result[name] = set(ids)
    return result


def select_patient_ids(
    patient_ids: Sequence[str],
    split_json: Optional[str],
    split: str,
) -> List[str]:
    normalized = [str(patient_id) for patient_id in patient_ids]
    if split_json is None:
        if split != "all":
            raise ValueError(f"split {split!r} requires split_json.")
        return normalized
    manifest = load_split_manifest(split_json)
    dataset_ids = set(normalized)
    manifest_ids = set().union(*manifest.values()) if manifest else set()
    missing = sorted(dataset_ids - manifest_ids)
    unknown = sorted(manifest_ids - dataset_ids)
    if missing or unknown:
        details = []
        if missing:
            details.append(f"{len(missing)} dataset IDs are missing")
        if unknown:
            details.append(f"{len(unknown)} IDs are unknown")
        raise ValueError("patient split manifest does not exactly cover the dataset: " + "; ".join(details))
    if split == "all":
        return normalized
    if split not in manifest:
        raise ValueError(
            f"split {split!r} not found in {split_json}; available: {sorted(manifest)}"
        )
    keep = manifest[split]
    return [patient_id for patient_id in normalized if patient_id in keep]


def set_seed(seed: int):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False


def resolve_device(value: str) -> torch.device:
    """Resolve ``auto`` safely and reject unavailable accelerator requests."""
    normalized = str(value).strip().lower()
    if normalized == "auto":
        if torch.cuda.is_available():
            return torch.device("cuda")
        mps = getattr(torch.backends, "mps", None)
        if mps is not None and mps.is_available():
            return torch.device("mps")
        return torch.device("cpu")
    device = torch.device(value)
    if device.type == "cuda" and not torch.cuda.is_available():
        raise RuntimeError("CUDA was requested but is not available; use train.device: auto or cpu.")
    if device.type == "cuda" and device.index is not None:
        if device.index < 0 or device.index >= torch.cuda.device_count():
            raise RuntimeError(f"CUDA device index {device.index} is not available.")
    if device.type == "mps":
        mps = getattr(torch.backends, "mps", None)
        if mps is None or not mps.is_available():
            raise RuntimeError("MPS was requested but is not available; use train.device: auto or cpu.")
    return device


def setup_logger(
    log_dir: Optional[str] = None,
    name: str = "reta",
    level: str = "INFO",
):
    """Create a console logger and, when requested, a run log file."""
    try:
        from loguru import logger

        logger.remove()
        logger.add(lambda message: print(message, end=""), level=level)
        if log_dir is not None:
            os.makedirs(log_dir, exist_ok=True)
            logger.add(
                os.path.join(log_dir, f"{name}.log"),
                level=level,
                enqueue=True,
                backtrace=False,
                diagnose=False,
            )
        return logger
    except Exception:
        import logging

        logger = logging.getLogger(name)
        logger.setLevel(getattr(logging, level.upper(), logging.INFO))
        logger.handlers = []
        logger.propagate = False

        formatter = logging.Formatter(
            "[%(asctime)s] %(levelname)s %(name)s: %(message)s"
        )
        console = logging.StreamHandler()
        console.setLevel(getattr(logging, level.upper(), logging.INFO))
        console.setFormatter(formatter)
        logger.addHandler(console)

        if log_dir is not None:
            os.makedirs(log_dir, exist_ok=True)
            file_handler = logging.FileHandler(
                os.path.join(log_dir, f"{name}.log"),
                encoding="utf-8",
            )
            file_handler.setLevel(getattr(logging, level.upper(), logging.INFO))
            file_handler.setFormatter(formatter)
            logger.addHandler(file_handler)
        return logger


class EntityTokenMapper:
    """Validated shared namespace for processed and external entities."""

    def __init__(
        self,
        base_mapping: Mapping[str, Any],
        external_mapping: Optional[Mapping[str, Any]],
        base_vocab_size: int,
    ):
        base_vocab_size = int(base_vocab_size)
        if base_vocab_size <= 0:
            raise ValueError("base_vocab_size must be positive.")

        base = _integer_mapping(base_mapping, "base token mapping")
        if len(base) != base_vocab_size:
            raise ValueError(
                f"base token mapping has {len(base)} entries; expected {base_vocab_size}."
            )
        base_ids = list(base.values())
        if len(set(base_ids)) != len(base_ids) or set(base_ids) != set(range(base_vocab_size)):
            raise ValueError(
                "base token mapping must contain every contiguous ID in "
                f"[0, {base_vocab_size - 1}] exactly once."
            )

        external = _integer_mapping(external_mapping, "external token mapping")
        redefined = sorted(set(base) & set(external))
        if redefined:
            raise ValueError(
                "external token mapping redefines processed entities: "
                + ", ".join(redefined[:5])
            )
        external_ids = list(external.values())
        if len(set(external_ids)) != len(external_ids):
            raise ValueError("external entities must have unique token IDs.")
        expected_ids = set(range(base_vocab_size, base_vocab_size + len(external)))
        if set(external_ids) != expected_ids:
            raise ValueError(
                "external token IDs must be contiguous and begin at "
                f"{base_vocab_size}; expected {sorted(expected_ids)}."
            )

        self.base_mapping = base
        self.external_mapping = external
        self.mapping = dict(base)
        self.mapping.update(external)
        self.base_vocab_size = base_vocab_size
        self.vocab_size = base_vocab_size + len(external)

    @staticmethod
    def from_sources(
        name_to_token: Optional[Dict[str, int]] = None,
        entity_to_token_json: Optional[str] = None,
        base_vocab_size: Optional[int] = None,
    ) -> "EntityTokenMapper":
        """Build a mapper from processed ontology tokens plus external KG ids."""
        if name_to_token is None:
            raise ValueError("processed data is missing vocab.name_to_token.")
        if base_vocab_size is None:
            base_vocab_size = len(name_to_token)
        external: Mapping[str, Any] = {}
        if entity_to_token_json is not None:
            external = load_json_object_strict(
                entity_to_token_json,
                "external token mapping",
            )
        return EntityTokenMapper(name_to_token, external, base_vocab_size)

    def to_token(self, entity_id: str) -> Optional[int]:
        return self.mapping.get(str(entity_id))


class PoolAlignedTokenIndex:
    """Map template entities into the encoder's learnable embedding table.

    Each mapped token receives the normalized mean of every template vector
    whose medoid subgraph contains that token. Stage 1 uses these vectors to
    initialize the corresponding encoder rows; retrieval then reads the
    encoder's current, learnable code embeddings.
    """

    def __init__(self, pool: Any, mapper: EntityTokenMapper):
        matrix = np.asarray(pool.P, dtype=np.float32)
        if matrix.ndim != 2 or matrix.shape[0] == 0 or matrix.shape[1] == 0:
            raise ValueError("knowledge pool must contain a non-empty vector matrix.")
        if len(pool.templates) != matrix.shape[0]:
            raise ValueError("knowledge pool template/vector counts do not match.")
        self.dim = int(matrix.shape[1])

        vectors_by_token: Dict[int, List[np.ndarray]] = {}
        unmapped_entities: Set[str] = set()
        for template, vector in zip(pool.templates, matrix):
            entities = list(template.medoid.subgraph_nodes)
            if template.medoid.root_concept_id not in entities:
                entities.append(template.medoid.root_concept_id)
            tokens = set()
            for entity in entities:
                token = entity if isinstance(entity, int) else mapper.to_token(entity)
                if token is None:
                    unmapped_entities.add(str(entity))
                    continue
                token = int(token)
                if token < 0 or token >= mapper.vocab_size:
                    raise ValueError(
                        f"template {template.template_id} maps {entity!r} to invalid token {token}."
                    )
                tokens.add(token)
            for token in tokens:
                vectors_by_token.setdefault(token, []).append(vector)

        if unmapped_entities:
            examples = ", ".join(sorted(unmapped_entities)[:5])
            raise ValueError(
                "template pool contains unmapped entities; run `reta build-entity-map` "
                f"for this processed dataset and pool (examples: {examples})."
            )

        self._vectors: Dict[int, np.ndarray] = {}
        for token, vectors in vectors_by_token.items():
            mean = np.mean(np.stack(vectors, axis=0), axis=0).astype(np.float32)
            norm = float(np.linalg.norm(mean))
            if norm > 0.0:
                self._vectors[token] = mean / norm
        if not self._vectors:
            raise ValueError(
                "no knowledge-template entity can be mapped to the processed token namespace."
            )
        self.processed_tokens = {
            token for token in self._vectors if token < mapper.base_vocab_size
        }
        if not self.processed_tokens:
            raise ValueError(
                "no processed ICD/CCS token overlaps any knowledge-template node."
            )
        self.processed_coverage = len(self.processed_tokens) / float(mapper.base_vocab_size)

    def initialize_embedding_table(self, embedding_weight: torch.Tensor) -> int:
        """Copy pool-aligned vectors into their mapped learnable rows."""

        if not torch.is_tensor(embedding_weight) or embedding_weight.ndim != 2:
            raise ValueError("embedding_weight must be a two-dimensional tensor.")
        if int(embedding_weight.shape[1]) != self.dim:
            raise ValueError(
                f"embedding dimension {embedding_weight.shape[1]} does not match "
                f"knowledge-pool dimension {self.dim}."
            )
        token_ids = sorted(self._vectors)
        if token_ids[-1] >= int(embedding_weight.shape[0]):
            raise ValueError("pool-aligned token exceeds the embedding-table vocabulary.")
        indices = torch.tensor(token_ids, dtype=torch.long, device=embedding_weight.device)
        vectors = torch.as_tensor(
            np.stack([self._vectors[token] for token in token_ids], axis=0),
            dtype=embedding_weight.dtype,
            device=embedding_weight.device,
        )
        with torch.no_grad():
            embedding_weight.index_copy_(0, indices, vectors)
        return len(token_ids)


def encoder_code_embedding_lookup(encoder: Any) -> Callable[[int], np.ndarray]:
    """Return a retrieval lookup backed by the encoder's live embedding table."""

    try:
        weight = encoder.embed.emb.weight
    except AttributeError as exc:
        raise ValueError("encoder is missing embed.emb.weight.") from exc
    if not torch.is_tensor(weight) or weight.ndim != 2:
        raise ValueError("encoder embed.emb.weight must be a two-dimensional tensor.")

    def lookup(token: int) -> np.ndarray:
        token = int(token)
        if token < 0 or token >= int(weight.shape[0]):
            raise ValueError(f"code token {token} is outside the encoder vocabulary.")
        return (
            weight[token]
            .detach()
            .to(device="cpu", dtype=torch.float32)
            .numpy()
            .copy()
        )

    return lookup


def fold_policy_state_for_retrieval(
    history_current_state: Any,
    dim: int,
) -> np.ndarray:
    """Fold a ``[history; current]`` GRU state into normalized pool space."""

    dim = int(dim)
    if dim <= 0:
        raise ValueError("retrieval-state dimension must be positive.")
    if torch.is_tensor(history_current_state):
        state = (
            history_current_state.detach()
            .to(device="cpu", dtype=torch.float32)
            .numpy()
        )
    else:
        state = np.asarray(history_current_state, dtype=np.float32)
    if state.ndim != 1 or int(state.shape[0]) != 2 * dim:
        raise ValueError(f"policy state must be one-dimensional with length {2 * dim}.")
    if not np.isfinite(state).all():
        raise ValueError("policy state must contain only finite values.")
    folded = (state[:dim] + state[dim:]) * 0.5
    norm = float(np.linalg.norm(folded))
    if norm > 0.0:
        folded = folded / norm
    return folded.astype(np.float32, copy=False)


def visit_retrieval_tokens(visit: Mapping[str, Any]) -> List[int]:
    """Return deduplicated observed ICD tokens used by Eq. 1 retrieval."""

    ordered = []
    seen = set()
    for raw_token in visit.get("icd_tokens", []):
        token = int(raw_token)
        if token not in seen:
            seen.add(token)
            ordered.append(token)
    if not ordered:
        raise ValueError("visit has no observed ICD retrieval tokens.")
    return ordered


def template_to_subgraph(template_medoid: Dict[str, Any], mapper: EntityTokenMapper) -> Optional[TemplateSubgraph]:
    """GroundedTemplate dict -> TemplateSubgraph (token ids)."""
    nodes = template_medoid.get("subgraph_nodes", [])
    edges = template_medoid.get("subgraph_edges", [])

    token_nodes: List[int] = []
    node_index: Dict[int, int] = {}

    for n in nodes:
        tok = n if isinstance(n, int) else mapper.to_token(n)
        if tok is None:
            continue
        tok = int(tok)
        if tok not in node_index:
            node_index[tok] = len(token_nodes)
            token_nodes.append(tok)

    if len(token_nodes) == 0:
        return None

    ei_u: List[int] = []
    ei_v: List[int] = []
    for u, v in edges:
        tu = u if isinstance(u, int) else mapper.to_token(u)
        tv = v if isinstance(v, int) else mapper.to_token(v)
        if tu is None or tv is None:
            continue
        tu, tv = int(tu), int(tv)
        if tu not in node_index or tv not in node_index:
            continue
        iu, iv = node_index[tu], node_index[tv]
        if iu == iv:
            continue
        # undirected
        ei_u += [iu, iv]
        ei_v += [iv, iu]

    edge_index = torch.tensor([ei_u, ei_v], dtype=torch.long) if len(ei_u) else torch.zeros((2, 0), dtype=torch.long)
    return TemplateSubgraph(node_ids=token_nodes, edge_index=edge_index)


def template_vector_tensor(template: Any, dim: int, device: Optional[torch.device] = None) -> torch.Tensor:
    """Return a template vector in the validated model/pool dimension."""
    v = torch.tensor(template.vector, dtype=torch.float32, device=device)
    dim = int(dim)
    if v.ndim != 1 or v.numel() != dim:
        raise ValueError(
            f"template vector has shape {tuple(v.shape)}, expected ({dim},)."
        )
    return v


class TrajectorySampler:
    """Sample full patient trajectories from processed.pt for RL rollouts."""

    def __init__(
        self,
        processed_path: str,
        split_json: Optional[str] = None,
        split: str = "all",
    ):
        data = load_processed_data(processed_path)
        self.trajectories = data["trajectories"]
        self.meta = data["meta"]
        self.vocab = data.get("vocab", {})
        self.patient_ids = select_patient_ids(
            list(self.trajectories.keys()),
            split_json,
            split,
        )
        if not self.patient_ids:
            raise ValueError(f"no patients are available for split {split!r}.")

    def sample_patients(self, n: int) -> List[str]:
        n = min(int(n), len(self.patient_ids))
        return random.sample(self.patient_ids, n)

    def get_patient_traj(self, patient_id: str) -> List[Dict[str, Any]]:
        return self.trajectories[str(patient_id)]
